/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/contact': typeof ContactRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/videos': typeof VideosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/contact': typeof ContactRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/videos': typeof VideosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts': typeof AdminPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/contact': typeof ContactRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/videos': typeof VideosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/coach'
    | '/contact'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/videos'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/team'
    | '/admin/videos'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/admin/'
    | '/categories/'
    | '/admin/posts/$id'
    | '/admin/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/coach'
    | '/contact'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/videos'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/team'
    | '/admin/videos'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/admin'
    | '/categories'
    | '/admin/posts/$id'
    | '/admin/posts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/coach'
    | '/contact'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/videos'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/team'
    | '/admin/videos'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/admin/'
    | '/categories/'
    | '/admin/posts/$id'
    | '/admin/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CoachRoute: typeof CoachRoute
  ContactRoute: typeof ContactRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VideosRoute: typeof VideosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CoachRoute: CoachRoute,
  ContactRoute: ContactRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VideosRoute: VideosRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
